### ISSUE TITLE
no updates?

### ISSUE THREAD

**Issue by ekalaya2015** [netdata/netdata-grafana-datasource-plugin#24]
Hi,
I like this plugin but it seems there is no update lately even though netdata itself upgraded version many times.

**Comment by witalisoft** [comment]
Hello,

There was no recent changes because we're preparing to release the plugin in the Grafana Catalog.

**Comment by hugovalente-pm** [comment]
sorry for the long wait but the plugin has finally gone through the singing proces.
it is now available on Grafana plugin marketplace https://grafana.com/grafana/plugins/all-plugins/?search=netdata

![image](https://github.com/netdata/netdata-grafana-datasource-plugin/assets/82235632/4dd41494-b09d-41f1-ada7-36ea03dc5131)
